// src/lib/components/footer.svelte
<script lang="ts">
  import Github from "lucide-svelte/icons/github";
  import Gitlab from "lucide-svelte/icons/gitlab";
</script>

<footer class="footer items-center py-4 bg-neutral text-neutral-content">
  <aside class="items-center grid-flow-col mx-2">
    <a class="btn text-xl btn-ghost" href="/">nickbland.dev</a>
    <p>
      Copyright © 2024 - All right reserved | <a
        class="link"
        href="https://git.nickbland.dev/NickBland/website-2">Source Code</a
      > | Made with ❤️ using SvelteKit
    </p>
  </aside>
  <nav class="grid-flow-col gap-4 md:place-self-center md:justify-self-end mx-2">
    <div class="tooltip" data-tip="GitHub">
      <a
        role="button"
        class="btn btn-ghost hover:shadow-lg"
        aria-label="Find me at my GitHub"
        href="https://github.com/NickBland"><Github /></a
      >
    </div>
    <div class="tooltip" data-tip="GitLab">
      <a
        role="button"
        class="btn btn-ghost hover:shadow-lg"
        aria-label="Find me at my GitLab"
        href="https://git.nickbland.dev/NickBland"><Gitlab /></a
      >
    </div>
  </nav>
</footer>

// components/footer.tsx
import Link from "next/link";
import {IoLogoGithub, IoLogoGitlab} from "react-icons/io5";

export const Footer = () => {
    return (
        <div>
            <footer className="footer grid w-full grid-flow-row place-items-center text-center gap-y-10 gap-x-4 text-sm p-10 dark:bg-black bg-white dark:text-white text-black rounded">
                <div className="grid grid-flow-col gap-4">
                    <Link href="/"><a className="link link-hover">Home</a></Link>
                    <Link href="/"><a className="link link-hover">Home 2</a></Link>
                    <Link href="/"><a className="link link-hover">Home 3</a></Link>
                </div>
                <div>
                <div className="grid grid-flow-col gap-4">
                    <Link href="https://github.com/NickBland"><a><IoLogoGithub></IoLogoGithub></a></Link>
                    <Link href="https://git.nickbland.dev/explore"><a><IoLogoGitlab></IoLogoGitlab></a></Link>
                    </div>
                </div>
                <div>
                    <p>Made with ❤️ by Nick Bland</p>
                </div>
            </footer>
        </div>
    );
}
